export const AUTH_FORM_LOGIN = "AUTH_FORM_LOGIN";
export const AUTH_FORM_LOGIN_ERROR = "AUTH_FORM_LOGIN_ERROR";

export const AUTH_FORM_SIGNUP = "AUTH_FORM_SIGNUP";
export const AUTH_FORM_SIGNUP_ERROR = "AUTH_FORM_SIGNUP_ERROR";

export const AUTH_FORM_SOCIAL = "AUTH_FORM_SOCIAL";
export const AUTH_FORM_SOCIAL_ERROR = "AUTH_FORM_SOCIAL_ERROR";

export const AUTH_FORM_FORGOT_PASSWORD = "AUTH_FORGOT_PASSWORD";
export const AUTH_FORM_FORGOT_PASSWORD_ERROR = "AUTH_FORGOT_PASSWORD_ERROR";
