export const SET_VALUE = "SET_VALUE";
export const TOGGLE_STATE = "TOGGLE_STATE";
export const RESET_FEEDBACK_FORM = "RESET_FEEDBACK_FORM";
export const FEEDBACK_FORM_SUBMIT = "FEEDBACK_FORM_SUBMIT";
export const FEEDBACK_FORM_SUBMIT_ERROR = "FEEDBACK_FORM_SUBMIT_ERROR";
