export const ADD_OPTION = "ADD_OPTION";
export const REMOVE_OPTION = "REMOVE_OPTION";
export const REMOVE_ALL_OPTIONS = "REMOVE_ALL_OPTIONS";
export const TOGGLE_STATE = "TOGGLE_STATE";
export const SET_VALUE = "SET_VALUE";
export const SET_LOADING = "SET_LOADING";
export const SET_POSTS = "SET_POSTS";
export const FETCH_POSTS = "FETCH_POSTS";
export const ERROR_POSTS = "ERROR_POSTS";
export const NEXT_PAGE = "NEXT_PAGE";
export const SET_PAGE = "SET_PAGE";
export const RESET_PAGE = "RESET_PAGE";
export const SET_LIKE = "SET_LIKE";
export const SET_DELETE_MODAL_VISIBILITY = "SET_DELETE_MODAL_VISIBILITY";

export const DELETE_MODAL_HIDE = "DELETE_MODAL_HIDE";
export const DELETE_MODAL_POST = "DELETE_MODAL_POST";
export const DELETE_MODAL_COMMENT = "DELETE_MODAL_COMMENT";
