export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION";
export const CREATE_ORGANIZATION_ERROR = "CREATE_ORGANIZATION_ERROR";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
// export const FETCH_ORGANIZATION = "FETCH_ORGANIZATION";
// export const FETCH_ORGANIZATION_ERROR = "FETCH_ORGANIZATION_ERROR";
// export const FETCH_ORGANIZATION_SUCCESS = "FETCH_ORGANIZATION_SUCCESS";
