export const POSTS_ACTIONS = {
  SET_LOADING: "SET_LOADING",
  SET_POSTS: "SET_POSTS",
  FETCH_POSTS: "FETCH_POSTS",
  ERROR_POSTS: "ERROR_POSTS",
  NEXT_PAGE: "NEXT_PAGE",
  RESET_PAGE: "RESET_PAGE",
  SET_LIKE: "SET_LIKE",
  SET_DELETE_MODAL_VISIBILITY: "SET_DELETE_MODAL_VISIBILITY",
  DELETE_MODAL_HIDE: "DELETE_MODAL_HIDE",
  DELETE_MODAL_POST: "DELETE_MODAL_POST",
  DELETE_MODAL_COMMENT: "DELETE_MODAL_COMMENT",
};
