export const AUTH_SUCCESS = "AUTH_LOGIN";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const FORGOT_PASSWORD_REQUEST_SUCCESS =
  "FORGOT_PASSWORD_REQUEST_SUCCESS";
export const SET_USER = "SET_USER";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_ORGANISATION_INDEX = "SET_ORGANISATION_INDEX";
