module.exports = {
  nav: {
    prefix: "NAV",
    login: "_SI",
    register: "_JN",
    aboutUs: "_AU",
    addOrg: "_ADO",
    feed: "_HB",
    feedback: "_FDB",
    inbox: "_IBX"
  },
  homePage: {
    prefix: "HP",
    requestHelp: "_RE",
    offerHelp: "_OF",
    viewCommPost: "_VHB",
  },
  wizardNav: {
    next: "_NE",
    back: "_BA",
    skip: "_SK",
    step: "S",
    submit: "_SUB",
    showAnywhere: "_SA",
    enterEmail: "_EE",
  },
  locationInput: {
    enterAddress: "_EAZ",
    shareLocation: "_SL",
  },
  requestHelp: {
    prefix: "RE",
    medical: "_MH",
    other: "_OH",
  },
  post: {
    prefix: "PO",
    like: "_LK",
    comment: "_CM",
    share: "_SH",
    viewMore: "_VM",
    writeComment: "_WC",
    createPost: "_CP",
    allPost: "_AP",
    filterPost: "_FI",
    quitFilters: "_QF",
    viewResults: "_VR",
    requestOffer: "_RO",
    location: "_LO",
    providers: "_PV",
    type: "_TP",
    orgBtn: "_ORG",
    individualBtn: "_IN",
    button: "_PO",
  },
  user: {
    completedPrefix: "PC",
    profilePrefix: "PR",
  },
  organisation: {
    orgPrefix: "ORG",
    completedPrefix: "COC",
    createOrgProfPrefix: "COP",
    createNew: "_CN",
  },
  profile: {
    createProfile: "_CPR",
    viewProfile: "_VP",
    continuePosting: "_CNP",
    continueToFeed: "_CF",
    modify: "_MOD",
  },
  sign: {
    inPrefix: "SI",
    upPrefix: "SU",
    in: "_SI",
    up: "_JN",
  },

  social: {
    facebook: "_FB",
    google: "_GG",
    linkedin: "_LN",
  },
  offerHelp: {
    prefix: "OF",
    volunteer: "_VO",
    donor: "_DI",
    orgbtn: "_ORG",
  },
  feed: {
    prefix: "HB",
  },
  providersFilters: {
    individual: "_IN",
    startUp: "_ST",
    company: "_CMP",
    community: "_CM",
    government: "_GOV",
    nonProfit: "_NP",
    university: "_UN",
    healthCareProvider: "_HCP",
    others: "_OT",
  },
  typeFilter: {
    medicalSupplies: "_MS",
    groceriesFood: "_GF",
    business: "_BS",
    education: "_EDU",
    legal: "_LE",
    wellbeingMental: "_WM",
    entertainment: "_ENT",
    information: "_IF",
    funding: "_FU",
    researchAndDevelopment: "_RD",
    tech: "_TC",
    other: "_OT",
  },
};
