module.exports = {
  nav: {
    prefix: "NAV",
    login: "_SI",
    register: "_JN",
    aboutUs: "_AU",
    addOrg: "_ADO",
    feed: "_HB",
    feedback: "_FDB",
    inbox: "_INB",
    language: "_LS",
    switch: "_SWC",
    notifications: "_NOT",
  },
  homePage: {
    prefix: "HP",
    requestHelp: "_RE",
    offerHelp: "_OF",
    viewCommPost: "_VHB",
  },
  wizardNav: {
    next: "_NE",
    back: "_BA",
    skip: "_SK",
    step: "S",
    submit: "_SUB",
    showAnywhere: "_SA",
    enterEmail: "_EE",
  },
  locationInput: {
    enterAddress: "_EAZ",
    shareLocation: "_SL",
  },
  requestHelp: {
    prefix: "RE",
    medical: "_MH",
    other: "_OH",
  },
  post: {
    prefix: "PO",
    like: "_LK",
    comment: "_CM",
    share: "_SH",
    viewMore: "_VM",
    writeComment: "_WC",
    createPost: "_CP",
    allPost: "_AP",
    filterPost: "_FI",
    quitFilters: "_QF",
    viewResults: "_VR",
    requestOffer: "_RO",
    location: "_LO",
    providers: "_PV",
    type: "_TP",
    orgBtn: "_ORG",
    individualBtn: "_IN",
    button: "_PO",
    delete: "_DEL",
    edit: "_EDT",
  },
  user: {
    completedPrefix: "PC",
    profilePrefix: "PR",
  },
  organisation: {
    orgPrefix: "ORG",
    completedPrefix: "COC",
    createOrgProfPrefix: "COP",
    createNew: "_CN",
    email: "_EM",
  },
  profile: {
    createProfile: "_CPR",
    viewProfile: "_VP",
    viewProfilePrefix: "VP",
    continuePosting: "_CNP",
    continueToFeed: "_CF",
    modify: "_MOD",
    uploadAvatar: "_UA",
    verifyAccount: "_VA",
    verifyPopup: "_VAV",
    getVerify: "_VAV_GV",
    cancelVerify: "_CV",
    accountVerified: "_AV",
    checkBadge: "_AV_CB"
  },
  sign: {
    inPrefix: "SI",
    upPrefix: "SU",
    in: "_SI",
    up: "_JN",
  },

  social: {
    facebook: "_FB",
    google: "_GG",
    linkedin: "_LN",
  },
  offerHelp: {
    prefix: "OF",
    volunteer: "_VO",
    donor: "_DI",
    orgbtn: "_ORG",
  },
  feed: {
    prefix: "HB",
  },
  providersFilters: {
    individual: "_IN",
    startUp: "_ST",
    company: "_CMP",
    community: "_CM",
    government: "_GOV",
    nonProfit: "_NP",
    university: "_UN",
    healthCareProvider: "_HCP",
    others: "_OT",
  },
  typeFilter: {
    medicalSupplies: "_MS",
    groceriesFood: "_GF",
    business: "_BS",
    education: "_EDU",
    legal: "_LE",
    wellbeingMental: "_WM",
    entertainment: "_ENT",
    information: "_IF",
    funding: "_FU",
    researchAndDevelopment: "_RD",
    tech: "_TC",
    other: "_OT",
  },
  language: {
    "en-US": "_EN_US",
    "en-GB": "_EN_GB",
    pl: "_PL",
    "es-ES": "_ES_ES",
    "zh-TW": "_ZH_TW",
    de: "_DE",
    "zh-CN": "_ZN_CN",
    fr: "_FR",
    tr: "_TR",
    "hi-IN": "_HI_IN",
    "kn-IN": "_KN_IN",
    "mr-IN": "_MR_IN",
    "te-IN": "_TE_IN",
    "ms-MY": "_MS_MY",
    vi: "_VI",
    "mk-MK": "_MK_MK",
    "pt-PT": "_PT_PT",
    ar: "_AR",
    tl: "_TL",
    it: "_IT",
    ru: "_RU",
    th: "_TH",
    id: "_ID",
    "es-419": "_ES_419",
  },
  search: {
    prefix: "SCH",
    input: "_IN",
    category: "_CTG",
    posts: "_PO",
    individuals: "_PPL",
    organisations: "_ORG",
  },
  inbox: {
    prefix: "INB",
    suffix: "_INB",
    message: "_MS",
    post: "_PT",
    user: "_PPL",
    org: "_ORG",
    profile: "_PF",
    conversation: "_CON",
    request: "_RQT",
    settings: "_SET",
    accept: "_ACP",
    view: "_VW",
    ignore: "_IGN",
    block: "_BLK",
    unblock: "_UBLK",
    archive: "_ARC",
    unarchive: "_UARC",
    delete: "_DLT",
    edit: "_EDT",
    mobileEdit: "_EDT_MOB",
    sent: "_SNT",
  },
  aboutUs: {
    prefix: "AU",
    getInvolved: "_GI",
    goToHelp: "_VHB",
    linkedIn: "_LN",
    instagram: "_IG",
    twitter: "_TW",
    facebook: "_FB",
    joinVolunteer: "_GI_JV",
    joinAmbassador: "_GI_JA",
    joinStudentProgram: "_GI_JSP",
    pressRelease: "_PR",
    bookCall: "_BC",
  },
  notifications: {
    prefix: "NOT",
    like: "_LK",
    share: "_SH",
    comment: "_CM",
    settings: "_SET",
    report: "_RP",
  },
  moderation: {
    hide: "_HIP",
    unhide: "_UHIP",
    reportEventName: "CREATE_REPORT",
    keepPostEventName: "MOD_KEEP_POST",
    removePostEventName: "MOD_REMOVE_POST",
  },
};
