module.exports = {
  nav: {
    prefix: "NAV",
    login: "_SI",
    register: "_JN",
    aboutUs: "_AU",
    addOrg: "_ADO",
    feed: "_HB",
    feedBack: "_FDB",
  },
  homePage: {
    prefix: "HP",
    requestHelp: "_RE",
    offerHelp: "_OF",
    viewCommPost: "_VHB",
  },
  wizardNav: {
    next: "_NE",
    back: "_BA",
    skip: "_SK",
    step: "S",
    submit: "_SUB",
    showAnywhere: "_SA",
    enterEmail: "_EE",
  },
  locationInput: {
    enterAddress: "_EAZ",
    shareLocation: "_SL",
  },
  requestHelp: {
    prefix: "RE",
    medical: "_MH",
    other: "_OH",
  },
  post: {
    prefix: "PO",
    like: "_LK",
    comment: "_CM",
    share: "_SH",
    viewMore: "_VM",
    writeComment: "_WC",
    createPost: "_CP",
    orgBtn: "_ORG",
    individualBtn: "_IN",
    button: "_PO",
  },
  user: {
    completedPrefix: "PC",
    profilePrefix: "PR",
  },
  organisation: {
    orgPrefix: "ORG",
    completedPrefix: "COC",
    createOrgProfPrefix: "COP",
    createNew: "_CN",
  },
  profile: {
    createProfile: "_CPR",
    viewProfile: "_VP",
    continuePosting: "_CNP",
    continueToFeed: "_CF",
    modify: "_MOD",
  },
  sign: {
    inPrefix: "SI",
    upPrefix: "SU",
    in: "_SI",
    up: "_JN",
  },

  social: {
    facebook: "_FB",
    google: "_GG",
    linkedin: "_LK",
  },
  offerHelp: {
    prefix: "OF",
    volunteer: "_VO",
    donor: "_DI",
    orgbtn: "_ORG",
  },
};
