export const localization = {
  en: "en-US",
  "en-US": "en-US",
  "en-GB": "en-GB",
  ar: "ar",
  id: "id",
  "zh-TW": "zh-TW",
  nl: "nl",
  fr: "fr",
  de: "de",
  he: "he",
  it: "it",
  pt: "pt",
  ru: "ru",
  es: "es",
  tr: "tr",
  uk: "uk",
};

export const languages = {
  ar: { value: "العربية", text: "Arabic (العربية)" },
  id: { value: "Bahasa Indonesia", text: "Indonesian (Bahasa Indonesia)" },
  "zh-TW": { value: "繁體中文", text: "Chinese Traditional (繁體中文)" },
  nl: { value: "Nederlands", text: "Dutch (Nederlands)" },
  "en-US": { value: "English", text: "English (American English)" },
  "en-GB": { value: "English", text: "English (British English)" },
  fr: { value: "Français", text: "French (Français)" },
  de: { value: "Deutsch", text: "German (Deutsch)" },
  he: { value: "עברית", text: "Hebrew (עברית)" },
  it: { value: "Italiano", text: "Italian (Italiano)" },
  pt: { value: "Português", text: "Portuguese (Português)" },
  ru: { value: "русский", text: "Russian (русский)" },
  es: { value: "Español", text: "Spain (Español)" },
  tr: { value: "Türkçe", text: "Turkish (Türkçe)" },
  uk: { value: "Українська", text: "Ukrainian (Українська)" },
};
