export const SESSION_ACTIONS = {
  AUTH_SUCCESS: "AUTH_LOGIN",
  AUTH_ERROR: "AUTH_ERROR",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  FORGOT_PASSWORD_REQUEST_SUCCESS: "FORGOT_PASSWORD_REQUEST_SUCCESS",
  SET_USER: "SET_USER",
  SET_AUTH_LOADING: "SET_AUTH_LOADING",
  SET_ORGANISATION_INDEX: "SET_ORGANISATION_INDEX",
}
