name: Prettier

on:
  push:
    branches:
      - 'master'

  schedule:
    - cron:  '0 8 * * *'      # Check once a day regardless of commits
  repository_dispatch:
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prettify code
      uses: creyD/prettier_action@v2.2
      with:
        prettier_options: --write **/*.{js,md}
    - name: Commit push and pr
      uses: golfzaptw/action-commit-push-pr
      with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PREFIX_BRANCHES: 'update'
          DEFAULT_BRANCHES: 'master'
          COMMIT_MESSAGE: 'prettier'
          TITLE_PR: 'Prettier'
          BODY_PR: ''
