name: Prettier

on:
  push:
    branches:
      - 'master'

  schedule:
    - cron:  '0 8 * * *'      # Check once a day regardless of commits
  repository_dispatch:
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prettify code
      uses: creyD/prettier_action@v2.2
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
