name: Cypress end-to-end tests

on:
  pull_request:


jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup npm package
        run: npm init -y && npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: cypresse2e
          browser: chrome 

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots-in-headless-chrome
          path: cypresse2e/screenshots