name: Cypress end-to-end tests

on:
  pull_request:
    types: [opened]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          working-directory: cypresse2e
          start: npx cypress run
          wait-on: http://localhost:3000

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: screenshots-in-headless-chrome
          path: cypresse2e/screenshots